export default {
  "login": "Luganda1",
  "id": 62723878,
  "node_id": "MDQ6VXNlcjYyNzIzODc4",
  "avatar_url": "https://avatars3.githubusercontent.com/u/62723878?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Luganda1",
  "html_url": "https://github.com/Luganda1",
  "followers_url": "https://api.github.com/users/Luganda1/followers",
  "following_url": "https://api.github.com/users/Luganda1/following{/other_user}",
  "gists_url": "https://api.github.com/users/Luganda1/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Luganda1/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Luganda1/subscriptions",
  "organizations_url": "https://api.github.com/users/Luganda1/orgs",
  "repos_url": "https://api.github.com/users/Luganda1/repos",
  "events_url": "https://api.github.com/users/Luganda1/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Luganda1/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Tonny Luganda",
  "company": "self Employed",
  "blog": "",
  "location": "Los Angels Califonia",
  "email": null,
  "hireable": null,
  "bio": "Am self taught web developer thanks to all the free material on the internet. I'm looking forward to changing world with the knowledge i get.",
  "twitter_username": null,
  "public_repos": 6,
  "public_gists": 0,
  "followers": 0,
  "following": 5,
  "created_at": "2020-03-26T21:04:24Z",
  "updated_at": "2020-09-24T05:37:43Z"
}



/**{
  login: 'john-smilga',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/john-smilga',
  html_url: 'https://github.com/john-smilga',
  followers_url: 'https://api.github.com/users/john-smilga/followers',
  following_url:
    'https://api.github.com/users/john-smilga/following{/other_user}',
  gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://api.github.com/users/john-smilga/repos',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'John Smilga',
  company: 'Coding Addict',
  blog: 'www.johnsmilga.com',
  location: 'Los Angeles',
  email: null,
  hireable: null,
  bio: 'Creator of Coding Addict',
  twitter_username: 'john_smilga',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
};
*/